services:
  mongo:
    image: mongo:latest
    container_name: crud-rpg
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
